# Generated by Django 4.1 on 2022-08-11 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskmateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('starts', models.TimeField(default=datetime.datetime(2022, 8, 11, 15, 39, 41, 623569, tzinfo=datetime.timezone.utc))),
                ('ends', models.TimeField(default=datetime.datetime(2022, 8, 11, 15, 39, 41, 623569, tzinfo=datetime.timezone.utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taskmateuser')),
            ],
        ),
    ]
